### ISSUE TITLE
win7 -e 8 报错

### ISSUE THREAD

**Issue by jx-xing** [acising/kellect#3]
您好，我在win7环境下执行kellect.exe -e 8 -f test.json时，出现了kellect停止的错误

**Comment by xueboQiu** [comment]
@jx-xing 您好，感谢您提的意见，很抱歉没能及时回复您。我已经push了最新版本kellect，并且在“Windows 7 Enterprise SP1“上成功执行。release文件夹内包含已经编译好的kellect，您可以pull后使用。希望kellect能帮助到您。
note：请使用管理员模式运行kellect。

**Comment by jx-xing** [comment]
新版本的kellect也已经能够在我的win7系统下运行，非常感谢您的帮助
