### ISSUE TITLE
关于抓取日志中时间戳转换的问题

### ISSUE THREAD

**Issue by qianqiutiango** [acising/kellect#4]
您好！工具的功能很强大，我尝试抓取了一份测试数据进行解析，但是其中的时间戳貌似不是标准的时间戳，尝试解析了一下也没有成功，想请问一下您具体是用什么接口获取到的时间戳呢？应该如何解析比较好？谢谢！
下附图：
![image](https://user-images.githubusercontent.com/48014194/185339270-77e90259-f0c0-4f37-a06a-7825efdc8ff9.png)
![image](https://user-images.githubusercontent.com/48014194/185339606-446caea7-6ed7-4c76-acd3-0400c0bc542b.png)

**Comment by xueboQiu** [comment]
您好，非常感谢您提的意见。
关于kellect产生的timestamp是基于“windows nt”时间格式，即自1601年1月1日的UTC时间起的100纳秒数量。您给出的图片中是基于UNIX的事件戳转换。我们给到您在线转换”windows nt时间戳”网站：https://www.epochconverter.com/ldap

kellect不执行timestamp转换是为了提高性能，我们的研究暂时不需要绝对时间值。希望kellect能帮助到您！

**Comment by qianqiutiango** [comment]
非常感谢您的解答，不过该网站404了哈哈哈，我自己编写了代码来对时间戳进行转换，附在下面，如果有需要可以取用：
import  time
delta = 11644473600    # NT和UT时间戳相差11644473600秒
Windwos NT时间戳转Unix UT时间戳
def get_ut(nt=132985415490000000):
    ut = nt / (10 ** 7) - delta
    # t = time.gmtime(t)
    ut = round(ut,3)
    ut = int(ut * 1000)
    return ut
UNIX时间戳转常规时间格式
def timeStamp(timeNum): 
    timeStamp = float(timeNum/1000) 
    timeArray = time.localtime(timeStamp) 
    otherStyleTime = time.strftime("%Y-%m-%d %H:%M:%S", timeArray) 
    print(otherStyleTime)
ut = get_ut()
timeStamp(ut)

**Comment by xueboQiu** [comment]
非常感谢您提供的转换代码！后续我们可能会改进这个问题，请持续关注我们的动态，祝您工作顺利。
note：网站访问可能需要翻墙，我们这边可以正常访问。

**Comment by qianqiutiango** [comment]
我挂着梯子，甚至能google，但是还是打不开，不过问题不大，在线网站转换是很难支持我们的研究的
希望之后与贵团队多多交流，kellect节省了我们许多时间，不过在分析数据的过程中我也发现了一些疑惑点，如果有机会还要再向您请教，非常感谢！

**Comment by xueboQiu** [comment]
不客气，能帮助到你们是我们的荣幸。有疑问请多留言，我们会尽可能完善kellect或解答你们的相关疑问，再次祝您工作顺利。
note：非常抱歉，刚刚是我在网址后面多打了一个符号。我已将网址最后的“。”删除了。

**Comment by qianqiutiango** [comment]
收到，非常感谢，麻烦了！
