### ISSUE TITLE
您好，kellect工具经测试在win10、win11环境中无法采集日志

### ISSUE THREAD

**Issue by imiku3939** [acising/kellect#6]
kellect工具经测试在win10、win11环境中无法采集日志，可能是文件无法写入或者是采集不到
![image](https://user-images.githubusercontent.com/99156997/224531285-b97642c0-a45f-4019-84e2-180cc4b282e2.png)

**Comment by xueboQiu** [comment]
您好，我们刚刚下载了latest release版本的kellect，并且测试kellect在win10、win11中可以正常输出日志。win11似乎不会实时显示文件大小的变化，您直接使用vs vode打开即可。 @imiku3939

**Comment by imiku3939** [comment]
您好，我是下载了最新的代码包，使用了里面的kellect.exe，然后无法采集，测试使用release版可以使用，感谢回复！
